### ISSUE TITLE
Profile-page bug

### ISSUE THREAD

**Issue by PrinceBadru** [InnoSolve-Tech/GameAnvil#9]
## Tried adding link to the Profile card
- I added a link to the profile card to open the Artist page when It is clicked however I keep getting an error of page not found.  https://github.com/InnoSolve-Tech/GameAnvil/commit/780064968035ac3d3b9afa14f2e4d0a044779074

**Comment by BenziDarwin** [comment]
Did you check out how to configure routing for nextjs using the folder structure?
 Check this. https://nextjs.org/docs/pages/building-your-application/routing/pages-and-layouts. @PrinceBadru.

**Comment by BenziDarwin** [comment]
This has been fixed @PrinceBadru.
